# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QNy63yi3_Zag_yDQDYbdebmWlquKR3gY
"""

def function_name():
     
     print("Hello World, this is my first function")

def length(liste):
  s=0
  for i in liste:
    s+=1
  return(s)
a=[1,"gh",22]
print(length(a))

def operation(x,y,z):
      print((x+y)*z)
operation(5,3,2)

def test_5(a):
  if a<5:
    print(a,"lower than 5")
  elif a>5:
    print(a,"greater than 5")
  else:
    print(a,"equal 5")
print(test_5(4))

def subtract(a,b):
  
  x = int(a)
  y = int(b)
  z = x-y
  
  return z
print(subtract(6,5))

sum = lambda a,b,c : a+b+c
print(sum(2,6,3))

test = lambda date : date.split('-')[2]
date = '20-8-9'
print(test(date))

#First
def max(a,b,c):
  if a>b and a>c:
    return(a)
  elif b>a and b>c:
    return(b)
  elif c>a and c>b:
    return(c)
  else:
    print("no")

#Second

def calculation(a,b):
  x=int(a)-int(b)
  y=int(a)+int(b)
  return (x,y)
calculation(8,5)

#third
def sum(T):
  sum=0
  for i in range (0,len(T)):
      sum=sum+T[i]
  return sum
  
sum([1,5,6,7])

#4
def multiple(T):
  m=1
  for i in range (0,len(T)):
      m=m*T[i]
  return m

multiple([1,2,4])

def both(T):
  t1=list()
  t2=list()
  for i in range (0,len(T)):
    if i%2==0:
      t1.append(T[i])
    else:
      t2.append(T[i])
  print (sum(t1))
  print(multiple(t2))
both([1,2,3,4])

items=[n for n in input().split('-')]
items.sort()
print(items)

import math
c=50
h=30
value = []
items=[x for x in input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))

print(','.join(value))