# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PpAxAwRYJVEaW_iKVkSYwvpwpeJ68ZyD
"""

items=[3,1,5]
tot=1
for i in items:
  tot=tot*i
print(tot)

tup =[(1, 3), (3, 2), (2, 1)]
 lst = len(tup) 
 for i in range(0, lst): 
           
        for j in range(0, lst-i-1): 
            if (tup[j][-1] > tup[j + 1][-1]): 
                temp = tup[j] 
                tup[j]= tup[j + 1] 
                tup[j + 1]= temp 
        print(tup)

dict1 = {'a': 12, 'b': 25, 'c': 9}
dict2 = {'a': 100, 'b': 200, 'c': 300}
dict3 = {}
 
for key in dict2:
    if key in dict1:
        dict3[key] = dict2[key] + dict1[key]
    else:
        print("impossible")
         
print(dict3)

Dic1 = {}
num = int(input("type a number"))
for i in range(1, num+1):
    Dic1[i]=i*i
print(Dic1)